spring:
  profile:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/srast3/test-microservice.git
          search-paths:
            - "EmailServiceConfigProperties/{application}/{profile}"
eureka:
#  instance:
#    hostname: config-server
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://shashank-HP-Notebook:8761/eureka/