 node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/srast3/test-microservice.git', credentialsId: '', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

	stage('Deploy') {
	  sh 'java -jar target/EurekaServer-0.0.1-SNAPSHOT.jar'
	
        }

	stage ('Final') {
            build job: 'config-server-pipeline', wait: false
        }     
    }

}